import type { BioPart } from './types';

export const ALL_PARTS: BioPart[] = [
  {
    id: 'constitutive-promoter',
    category: 'promoter',
    name: 'Constitutive Promoter',
    label: 'CMV',
    color: '#3b82f6',
    description: 'Always active. Drives expression of any downstream gene.',
    strength: 2,
  },
  {
    id: 'strong-promoter',
    category: 'promoter',
    name: 'Strong Promoter',
    label: 'T7',
    color: '#2563eb',
    description: 'A very strong constitutive promoter. Maximum expression.',
    strength: 3,
  },
  {
    id: 'sugar-promoter',
    category: 'promoter',
    name: 'Sugar-Responsive Promoter',
    label: 'GAL1',
    color: '#f59e0b',
    description: 'Active only when galactose (sugar) is present.',
    signal: 'sugar',
    strength: 2,
  },
  {
    id: 'poison-promoter',
    category: 'promoter',
    name: 'Toxin-Responsive Promoter',
    label: 'TOX1',
    color: '#ef4444',
    description: 'Active only when toxin is present. Silenced by RepA protein.',
    signal: 'poison',
    strength: 2,
    repressedBy: 'RepA',
  },
  {
    id: 'repressible-promoter',
    category: 'promoter',
    name: 'Repressible Promoter',
    label: 'RPR',
    color: '#a78bfa',
    description: 'Always active — unless RepA protein is present, which silences it.',
    strength: 2,
    repressedBy: 'RepA',
  },
  {
    id: 'gfp-gene',
    category: 'gene',
    name: 'GFP Gene',
    label: 'GFP',
    color: '#22c55e',
    description: 'Produces Green Fluorescent Protein. Makes the cell glow green.',
    product: 'GFP',
  },
  {
    id: 'rfp-gene',
    category: 'gene',
    name: 'RFP Gene',
    label: 'RFP',
    color: '#ef4444',
    description: 'Produces Red Fluorescent Protein. Makes the cell glow red.',
    product: 'RFP',
  },
  {
    id: 'repressor-gene',
    category: 'gene',
    name: 'Repressor Gene',
    label: 'REP',
    color: '#a855f7',
    description: 'Produces RepA protein, which silences any promoter that RepA targets.',
    product: 'RepA',
  },
  {
    id: 'gfp-n-gene',
    category: 'gene',
    name: 'Split GFP (N-half)',
    label: 'GFP-N',
    color: '#86efac',
    description: 'Produces the N-terminal half of GFP. Needs the C-half to glow.',
    product: 'GFP-N',
  },
  {
    id: 'gfp-c-gene',
    category: 'gene',
    name: 'Split GFP (C-half)',
    label: 'GFP-C',
    color: '#4ade80',
    description: 'Produces the C-terminal half of GFP. Needs the N-half to glow.',
    product: 'GFP-C',
  },
  {
    id: 'activator-gene',
    category: 'gene',
    name: 'Activator Gene',
    label: 'ACT',
    color: '#06b6d4',
    description: 'Produces ActA protein, which activates the activator-responsive promoter.',
    product: 'ActA',
  },
  {
    id: 'activator-promoter',
    category: 'promoter',
    name: 'Activator-Responsive Promoter',
    label: 'ACTR',
    color: '#0891b2',
    description: 'Only active when ActA protein is present. Strong expression (strength 3).',
    strength: 3,
    activatedBy: 'ActA',
  },
  {
    id: 'weak-sugar-promoter',
    category: 'promoter',
    name: 'Weak Sugar Promoter',
    label: 'wGAL',
    color: '#d97706',
    description: 'Active when sugar is present, but weak — strength 1.',
    signal: 'sugar',
    strength: 1,
  },
  {
    id: 'toxin-promoter',
    category: 'promoter',
    name: 'Toxin Promoter',
    label: 'TOX2',
    color: '#dc2626',
    description: 'Active when toxin is present. Not affected by repressors.',
    signal: 'poison',
    strength: 2,
  },
  {
    id: 'insulin-gene',
    category: 'gene',
    name: 'Insulin Gene',
    label: 'INS',
    color: '#8b5cf6',
    description: 'Produces Insulin protein. Insulin does not fluoresce — you need an instrument to detect it.',
    product: 'Insulin',
  },
  {
    id: 'terminator',
    category: 'terminator',
    name: 'Terminator',
    label: 'TERM',
    color: '#6b7280',
    description: 'Stops transcription. Genes after this need a new promoter.',
  },
];

export const PARTS_MAP = new Map(ALL_PARTS.map(p => [p.id, p]));
