import type { PartDef } from './types';

export const PARTS_GRAMMAR: PartDef[] = [
  // ── Bacterial constitutive promoters ──────────────────────────────
  {
    id: 'bact-prom-const-weak',
    type: 'promoter',
    name: 'Weak Constitutive Promoter',
    label: 'J23105',
    color: '#60a5fa',
    description: 'Always active. Low expression (strength 1).',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 1,
  },
  {
    id: 'bact-prom-const-med',
    type: 'promoter',
    name: 'Constitutive Promoter',
    label: 'J23106',
    color: '#3b82f6',
    description: 'Always active. Moderate expression (strength 2).',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 2,
  },
  {
    id: 'bact-prom-const-strong',
    type: 'promoter',
    name: 'Constitutive Promoter (Anderson J23100)',
    label: 'J23100',
    color: '#2563eb',
    description: 'Always active. Strong bacterial expression from Anderson promoter J23100 (strength 5).',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 5,
  },
  // ── Bacterial inducible promoters ─────────────────────────────────
  {
    id: 'bact-prom-iptg',
    type: 'promoter',
    name: 'IPTG-Inducible Promoter',
    label: 'Plac',
    color: '#f59e0b',
    description: 'Active only when IPTG is present. Strength 2.',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 2,
    signal: 'iptg',
  },
  {
    id: 'bact-prom-ara',
    type: 'promoter',
    name: 'Arabinose-Inducible Promoter',
    label: 'PBAD',
    color: '#f97316',
    description: 'Active when arabinose is present. Inhibited by glucose. Strength 2.',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 2,
    signal: 'arabinose',
  },
  {
    id: 'bact-prom-atc',
    type: 'promoter',
    name: 'aTc-Inducible Promoter',
    label: 'Ptet',
    color: '#f59e0b',
    description: 'Active only when aTc is present. Strength 2.',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 2,
    signal: 'atc',
  },
  {
    id: 'bact-prom-toxin',
    type: 'promoter',
    name: 'Toxin-Signal Promoter',
    label: 'Ptox',
    color: '#ef4444',
    description: 'Active only when toxin signal is present. Strength 2.',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 2,
    signal: 'toxin',
  },
  // ── Bacterial repressible promoters ───────────────────────────────
  {
    id: 'bact-prom-laco',
    type: 'promoter',
    name: 'LacO Repressible Promoter',
    label: 'lacO',
    color: '#a78bfa',
    description: 'Active by default. Silenced when LacI repressor is present. Strength 2.',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 2,
    repressedBy: 'LacI',
  },
  {
    id: 'bact-prom-teto',
    type: 'promoter',
    name: 'TetO Repressible Promoter',
    label: 'tetO',
    color: '#c084fc',
    description: 'Active by default. Silenced when TetR repressor is present. Strength 2.',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 2,
    repressedBy: 'TetR',
  },
  // L18 specific: promoters that drive reporter A/B/C (each has a unique id so guide RNAs can target them)
  {
    id: 'bact-prom-g1',
    type: 'promoter',
    name: 'Constitutive Promoter (G1)',
    label: 'J23100-G1',
    color: '#22c55e',
    description: 'Strong constitutive promoter driving Gene1. Strength 3.',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 3,
  },
  {
    id: 'bact-prom-g2',
    type: 'promoter',
    name: 'Constitutive Promoter (G2)',
    label: 'J23100-G2',
    color: '#3b82f6',
    description: 'Strong constitutive promoter driving Gene2. Strength 3.',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 3,
  },
  {
    id: 'bact-prom-g3',
    type: 'promoter',
    name: 'Constitutive Promoter (G3)',
    label: 'J23100-G3',
    color: '#f59e0b',
    description: 'Strong constitutive promoter driving Gene3. Strength 3.',
    validHostModes: ['bacterial'],
    rnaPLoadRate: 3,
  },
  // ── Bacterial RBS ─────────────────────────────────────────────────
  {
    id: 'bact-rbs-weak',
    type: 'rbs',
    name: 'Weak Shine-Dalgarno Sequence (B0032-like)',
    label: 'SD-Weak',
    color: '#6b7280',
    description: 'Weak bacterial ribosome loading site, similar to B0032. About 50% translation efficiency.',
    validHostModes: ['bacterial'],
    translationRate: 0.5,
  },
  {
    id: 'bact-rbs-med',
    type: 'rbs',
    name: 'Medium Shine-Dalgarno Sequence (B0030-like)',
    label: 'SD-Med',
    color: '#9ca3af',
    description: 'Medium-strength bacterial ribosome loading site, similar to B0030. About 75% translation efficiency.',
    validHostModes: ['bacterial'],
    translationRate: 0.75,
  },
  {
    id: 'bact-rbs-strong',
    type: 'rbs',
    name: 'Strong Shine-Dalgarno Sequence (B0034-like)',
    label: 'SD-Strong',
    color: '#d1d5db',
    description: 'Strong bacterial ribosome loading site, similar to B0034. Full translation efficiency.',
    validHostModes: ['bacterial'],
    translationRate: 1.0,
  },
  // ── Bacterial genes ───────────────────────────────────────────────
  {
    id: 'gene-gfp',
    type: 'gene',
    name: 'GFP Gene',
    label: 'GFP',
    color: '#22c55e',
    description: 'Produces Green Fluorescent Protein.',
    validHostModes: ['bacterial', 'eukaryotic'],
    product: 'GFP',
  },
  {
    id: 'gene-rfp',
    type: 'gene',
    name: 'RFP Gene',
    label: 'RFP',
    color: '#ef4444',
    description: 'Produces Red Fluorescent Protein.',
    validHostModes: ['bacterial', 'eukaryotic'],
    product: 'RFP',
  },
  {
    id: 'gene-insulin',
    type: 'gene',
    name: 'Insulin Gene',
    label: 'INS',
    color: '#8b5cf6',
    description: 'Produces Insulin. Not fluorescent.',
    validHostModes: ['bacterial', 'eukaryotic'],
    product: 'Insulin',
  },
  {
    id: 'gene-enzyme1',
    type: 'gene',
    name: 'beta-galactosidase Gene (lacZ example)',
    label: 'lacZ',
    color: '#06b6d4',
    description: 'Encodes LacZ beta-galactosidase.',
    validHostModes: ['bacterial'],
    product: 'LacZ',
  },
  {
    id: 'gene-enzyme2',
    type: 'gene',
    name: 'chloramphenicol acetyltransferase Gene (cat example)',
    label: 'cat',
    color: '#0891b2',
    description: 'Encodes Cat chloramphenicol acetyltransferase.',
    validHostModes: ['bacterial'],
    product: 'Cat',
  },
  {
    id: 'gene-enzyme-a',
    type: 'gene',
    name: 'alpha-amylase Gene (amyE example)',
    label: 'amyE',
    color: '#10b981',
    description: 'Encodes AmyE alpha-amylase.',
    validHostModes: ['bacterial'],
    product: 'AmyE',
  },
  {
    id: 'gene-toxin-b',
    type: 'gene',
    name: 'CcdB Toxin Gene (ccdB)',
    label: 'ccdB',
    color: '#dc2626',
    description: 'Encodes CcdB toxin. CcdB is toxic when it accumulates above the safe threshold.',
    validHostModes: ['bacterial'],
    product: 'CcdB',
  },
  {
    id: 'gene-gene1',
    type: 'gene',
    name: 'Reporter A Gene',
    label: 'RptA',
    color: '#22c55e',
    description: 'Encodes reporter protein A.',
    validHostModes: ['bacterial'],
    product: 'Protein1',
  },
  {
    id: 'gene-gene2',
    type: 'gene',
    name: 'Reporter B Gene',
    label: 'RptB',
    color: '#3b82f6',
    description: 'Encodes reporter protein B.',
    validHostModes: ['bacterial'],
    product: 'Protein2',
  },
  {
    id: 'gene-gene3',
    type: 'gene',
    name: 'Reporter C Gene',
    label: 'RptC',
    color: '#f59e0b',
    description: 'Encodes reporter protein C.',
    validHostModes: ['bacterial'],
    product: 'Protein3',
  },
  {
    id: 'linker-flex',
    type: 'linker',
    name: 'Flexible Fusion Linker',
    label: 'Lnk',
    color: '#a78bfa',
    description: 'Keeps translation continuous from one coding sequence into the next, creating a fused protein.',
    validHostModes: ['bacterial', 'eukaryotic'],
  },
  {
    id: 'gene-dcas9',
    type: 'gene',
    name: 'dCas9 Gene',
    label: 'dCas9',
    color: '#7c3aed',
    description: 'Produces dCas9 protein. Combines with guide RNA to block specific promoters.',
    validHostModes: ['bacterial', 'eukaryotic'],
    product: 'dCas9',
    isDCas9: true,
  },
  {
    id: 'gene-repressor-laci',
    type: 'gene',
    name: 'LacI Repressor Gene',
    label: 'lacI',
    color: '#a855f7',
    description: 'Produces LacI, which silences lacO promoters.',
    validHostModes: ['bacterial'],
    product: 'LacI',
  },
  {
    id: 'gene-repressor-tetr',
    type: 'gene',
    name: 'TetR Repressor Gene',
    label: 'tetR',
    color: '#9333ea',
    description: 'Produces TetR, which silences tetO promoters.',
    validHostModes: ['bacterial'],
    product: 'TetR',
  },
  {
    id: 'gene-drug',
    type: 'gene',
    name: 'Drug Gene',
    label: 'Drug',
    color: '#ec4899',
    description: 'Produces the therapeutic Drug protein.',
    validHostModes: ['eukaryotic'],
    product: 'Drug',
  },
  {
    id: 'gene-cancer-activator',
    type: 'gene',
    name: 'Cancer-Sensor Activator Gene',
    label: 'Act-C',
    color: '#db2777',
    description: 'Encodes a synthetic activator protein used to mark cancer-cell context.',
    validHostModes: ['eukaryotic'],
    product: 'CancerActivator',
  },
  // ── Bacterial terminators ─────────────────────────────────────────
  {
    id: 'bact-term-strong',
    type: 'terminator',
    name: 'Strong Terminator',
    label: 'Term',
    color: '#6b7280',
    description: 'Stops transcription completely. Also stabilizes upstream messenger RNA.',
    validHostModes: ['bacterial'],
    readThroughPct: 0,
    mRNAStabilityBonus: 0.1,
  },
  {
    id: 'bact-term-leaky',
    type: 'terminator',
    name: 'Leaky Terminator',
    label: 'Leaky',
    color: '#9ca3af',
    description: 'Stops ~85% of transcription. ~15% read-through continues downstream.',
    validHostModes: ['bacterial'],
    readThroughPct: 0.15,
    mRNAStabilityBonus: 0,
  },
  // ── SsrA degradation tags ─────────────────────────────────────────
  {
    id: 'tag-ssra-laa',
    type: 'tag',
    name: 'SsrA-LAA Tag (Fast)',
    label: 'ssrA-LAA',
    color: '#f87171',
    description: 'Fast ClpXP degradation tag. Keeps protein level low. High ClpXP demand.',
    validHostModes: ['bacterial'],
    tagRate: 3,
    tagType: 'ssrA',
  },
  {
    id: 'tag-ssra-das',
    type: 'tag',
    name: 'SsrA-DAS Tag (Medium)',
    label: 'ssrA-DAS',
    color: '#fb923c',
    description: 'Medium ClpXP degradation tag. Moderate protein reduction.',
    validHostModes: ['bacterial'],
    tagRate: 2,
    tagType: 'ssrA',
  },
  {
    id: 'tag-ssra-aav',
    type: 'tag',
    name: 'SsrA-AAV Tag (Slow)',
    label: 'ssrA-AAV',
    color: '#fbbf24',
    description: 'Slow ClpXP degradation tag. Mild protein reduction.',
    validHostModes: ['bacterial'],
    tagRate: 1,
    tagType: 'ssrA',
  },
  // ── Guide RNA scaffolds (L18 / L19) ────────────────────────────────
  {
    id: 'grna-a',
    type: 'crispr',
    name: 'Guide RNA A',
    label: 'guide A',
    color: '#7c3aed',
    description: 'Directs dCas9 to block the reporter A promoter.',
    validHostModes: ['bacterial', 'eukaryotic'],
    targetPromoter: 'bact-prom-g1',
  },
  {
    id: 'grna-b',
    type: 'crispr',
    name: 'Guide RNA B',
    label: 'guide B',
    color: '#6d28d9',
    description: 'Directs dCas9 to block the reporter B promoter.',
    validHostModes: ['bacterial', 'eukaryotic'],
    targetPromoter: 'bact-prom-g2',
  },
  {
    id: 'grna-c',
    type: 'crispr',
    name: 'Guide RNA C',
    label: 'guide C',
    color: '#5b21b6',
    description: 'Directs dCas9 to block the reporter C promoter.',
    validHostModes: ['bacterial', 'eukaryotic'],
    targetPromoter: 'bact-prom-g3',
  },
  // ── Eukaryotic parts (L19) ────────────────────────────────────────
  {
    id: 'euk-prom-const-weak',
    type: 'promoter',
    name: 'Weak Eukaryotic Promoter',
    label: 'SV40w',
    color: '#60a5fa',
    description: 'Weak constitutive eukaryotic promoter. Strength 1.',
    validHostModes: ['eukaryotic'],
    rnaPLoadRate: 1,
  },
  {
    id: 'euk-prom-const-med',
    type: 'promoter',
    name: 'Eukaryotic Promoter',
    label: 'CMV',
    color: '#3b82f6',
    description: 'Moderate constitutive eukaryotic promoter. Strength 2.',
    validHostModes: ['eukaryotic'],
    rnaPLoadRate: 2,
  },
  {
    id: 'euk-prom-const-strong',
    type: 'promoter',
    name: 'Strong Eukaryotic Promoter',
    label: 'EF1α',
    color: '#2563eb',
    description: 'Strong constitutive eukaryotic promoter. Strength 3.',
    validHostModes: ['eukaryotic'],
    rnaPLoadRate: 3,
  },
  {
    id: 'euk-prom-cancer',
    type: 'promoter',
    name: 'Cancer-Marker Promoter',
    label: 'Pcancer',
    color: '#dc2626',
    description: 'Active only in cells expressing the cancer marker protein. Strength 2.',
    validHostModes: ['eukaryotic'],
    rnaPLoadRate: 2,
    signal: 'cancer-marker',
  },
  {
    id: 'euk-prom-nutrient',
    type: 'promoter',
    name: 'Nutrient-Responsive Promoter',
    label: 'Pnutr',
    color: '#f59e0b',
    description: 'Active when nutrient signal is present. Strength 2.',
    validHostModes: ['eukaryotic'],
    rnaPLoadRate: 2,
    signal: 'nutrient',
  },
  {
    id: 'euk-prom-nutrient-activator',
    type: 'promoter',
    name: 'Nutrient Promoter with Cancer Activator Site',
    label: 'Pnutr+Act',
    color: '#fb923c',
    description: 'Active only when nutrient signal is present and the cancer-sensor activator protein is present.',
    validHostModes: ['eukaryotic'],
    rnaPLoadRate: 2,
    signal: 'nutrient',
    activatedBy: 'CancerActivator',
  },
  {
    id: 'euk-prom-healthy',
    type: 'promoter',
    name: 'Healthy-Cell Promoter',
    label: 'Phealthy',
    color: '#22c55e',
    description: 'Active only in healthy cells expressing the healthy-cell marker. Strength 2.',
    validHostModes: ['eukaryotic'],
    rnaPLoadRate: 2,
    signal: 'healthy-marker',
  },
  // ── Kozak sequences (eukaryotic RBS equivalent) ───────────────────
  {
    id: 'euk-kozak-weak',
    type: 'rbs',
    name: 'Weak Kozak Sequence',
    label: 'Kozak-W',
    color: '#6b7280',
    description: 'Weak Kozak context. ~50% ribosome loading efficiency.',
    validHostModes: ['eukaryotic'],
    translationRate: 0.5,
  },
  {
    id: 'euk-kozak-strong',
    type: 'rbs',
    name: 'Strong Kozak Sequence',
    label: 'Kozak-S',
    color: '#d1d5db',
    description: 'Optimal Kozak context. Full ribosome loading efficiency.',
    validHostModes: ['eukaryotic'],
    translationRate: 1.0,
  },
  // ── Poly-A signal (eukaryotic terminator) ─────────────────────────
  {
    id: 'euk-polya',
    type: 'terminator',
    name: 'Poly-A Signal',
    label: 'pA',
    color: '#6b7280',
    description: 'Eukaryotic transcription terminator. Also stabilizes upstream messenger RNA (+20% output).',
    validHostModes: ['eukaryotic'],
    readThroughPct: 0,
    mRNAStabilityBonus: 0.2,
  },
  // ── Degrons (eukaryotic degradation tags) ─────────────────────────
  {
    id: 'tag-pest',
    type: 'tag',
    name: 'PEST Degron',
    label: 'PEST',
    color: '#f87171',
    description: 'Fast proteasomal degradation. High 26S proteasome demand.',
    validHostModes: ['eukaryotic'],
    tagRate: 3,
    tagType: 'degron',
  },
  {
    id: 'tag-cl1',
    type: 'tag',
    name: 'CL1 Degron',
    label: 'CL1',
    color: '#fb923c',
    description: 'Medium-rate proteasomal degradation.',
    validHostModes: ['eukaryotic'],
    tagRate: 2,
    tagType: 'degron',
  },
  {
    id: 'tag-auxin',
    type: 'tag',
    name: 'Auxin-Inducible Degron',
    label: 'AID',
    color: '#fbbf24',
    description: 'Slow degradation. Only active when auxin is present.',
    validHostModes: ['eukaryotic'],
    tagRate: 1,
    tagType: 'degron',
  },
  // ── Signal sequences (eukaryotic) ────────────────────────────────
  {
    id: 'nls',
    type: 'signal-sequence',
    name: 'Nuclear Localization Signal',
    label: 'NLS',
    color: '#8b5cf6',
    description: 'Routes upstream protein to the nucleus. Required for dCas9 to block DNA in eukaryotes.',
    validHostModes: ['eukaryotic'],
    destination: 'nucleus',
  },
  {
    id: 'signal-peptide',
    type: 'signal-sequence',
    name: 'Signal Peptide',
    label: 'SP',
    color: '#ec4899',
    description: 'Routes upstream protein to the secretory pathway.',
    validHostModes: ['eukaryotic'],
    destination: 'secretory',
  },
  // ── Enhancer (eukaryotic, orientation-independent) ────────────────
  {
    id: 'euk-enhancer',
    type: 'enhancer',
    name: 'Enhancer',
    label: 'Enh',
    color: '#f472b6',
    description: 'Boosts the nearest promoter by 1.5×. Orientation-independent.',
    validHostModes: ['eukaryotic'],
    boostFactor: 1.5,
  },
  // ── Guide RNA scaffolds for L19 ────────────────────────────────────
  {
    id: 'grna-not',
    type: 'crispr',
    name: 'Healthy-Promoter Guide RNA',
    label: 'guide NOT',
    color: '#7c3aed',
    description: 'Directs dCas9 to block the healthy-cell promoter.',
    validHostModes: ['eukaryotic'],
    targetPromoter: 'euk-prom-healthy',
  },
  {
    id: 'grna-drug-off',
    type: 'crispr',
    name: 'Drug-Promoter Guide RNA',
    label: 'guide Drug',
    color: '#6d28d9',
    description: 'Directs dCas9 to block the drug-expression promoter.',
    validHostModes: ['eukaryotic'],
    targetPromoter: 'euk-prom-nutrient-activator',
  },
];

export const PARTS_DEF_MAP = new Map<string, PartDef>(PARTS_GRAMMAR.map(p => [p.id, p]));
